name: Drugs
version: 6.1
main: me.theminddroid.drugs.DrugsPlugin
api-version: "1.15"
authors: [TheMindDroid]
description: Gives specific items drug effects
commands:
  drugs:
    description: An admin tool to spawn drugs.
    usage: /<command>
